POST http://127.0.0.1:8000/api/nlp/ HTTP/1.1
content-type: application/json; charset=utf-8

{    
    "content": "괜찮은데 이게 집전화 연결이 되있는거라서... 번호가 070으로 시작 하거든요... 근데 집전화는 뭐 문자가 못온다고 해서 그게 조금 아쉽고 로그인할때 이메일,비밀번호로만 할수 있게 해주시면 불편한점은 없겠네요..."
}