# Generated by Django 3.1 on 2020-08-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tags',
        ),
    ]
