# Generated by Django 3.1 on 2020-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20200814_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(help_text='PK AutoIncrement', primary_key=True, serialize=False),
        ),
    ]
